name: travel_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.1
  ionicons: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  image_path: "assets/icons/appLogo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/appLogoAndroid1.png"

flutter:
  uses-material-design: true

  assets:
    - assets/places/
    - assets/icons/
    - assets/

  fonts:
    - family: Cinzel
      fonts:
        - asset: fonts/Cinzel/Cinzel-VariableFont_wght.ttf
    - family: Cabin
      fonts:
        - asset: fonts/Cabin/Cabin-SemiBold-TTF.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Italic-VariableFont_wght.ttf

